diagram top-down
#    prddns "prd.finance.example.com"
    user "User" fill="#c0e1fc" color="#2196F3"

    subgraph "Tencent" fill="#f2f8f4" color="#88BDA4"
#        subgraph "Public subnets" line="dotted"
            pubclb "Public CLB" fill="#c0e1fc" color="#2196F3"
            vpn "VPN Endpoint" fill="#c0e1fc" color="#2196F3"
#        end
        subgraph "Private subnets" fill="#f2f8f4" color="#88BDA4"
            prvclb "Private CLB" fill="#c0e1fc" color="#2196F3"
#            prdtechdns "prd-tech.finance.example.com"
            cvm1 "Middleware" fill="#c0e1fc" color="#2196F3"
            cvm2 "Platform" fill="#c0e1fc" color="#2196F3"
            cvm3 "Application" fill="#c0e1fc" color="#2196F3"
            cvm4 "Algorithm" fill="#c0e1fc" color="#2196F3"
            cvm5 "MultiDim DB" fill="#c0e1fc" color="#2196F3"
            db "TDSQL DB" : cylinder fill="#c0e1fc" color="#2196F3"
        end
    end

    user --> vpn -- "tech.finance.example.com\n443" --> prvclb -- "443" --> cvm2
    user -- thick "finance.example.com\n443" --> pubclb -- thick "8088" --> cvm1

    vpn -- "22, 8088, 8080,\n30001, 1234" --> cvm1
    vpn -- "22, 443" --> cvm2
    vpn -- "22, 443" --> cvm3
    vpn -- "22, 443" --> cvm4
    vpn -- "22, 443" --> cvm5
    vpn -- "3306" --> db
