diagram top-down

    subgraph "Tencent Cloud Platform"

        vpn "VPN" fill="#99f"
        pub-clb "Public CLB" fill="#ccc"

        subgraph left-right "Dev VPC" fill="#ddd"
            subgraph "Dev/Digital Subnets" fill="#fff"
                prv-clb "Private CLB" fill="#ccc"
            end
            subgraph "Dev/Shared Subnets" fill="#fff"
                tke "TKE Cluster" fill="#f99"
            end
        end
    end

    pub-clb --> tke
    vpn --> prv-clb --> tke
